import React from "react";

export default function WhatsNext() {
  <ul></ul>;
  return (
    <>
      <div>Whats Next? - Features coming soon...</div>
      <ul>
        <li>
          {" "}
          Showing the Map when selecting the adress and showing all requests
          waiting for an offer with pinpoints
        </li>
        <li> Allowing to add up to 10 Addresses by a user</li>
        <li> Multiple image upload for each request</li>
        <li>
          {" "}
          Upload Image generated by AI based on the request text to enhance
          visuality
        </li>
        <li>
          {" "}
          Metrics / KPI to get visual information about my reuqests , offers and
          app usage
        </li>
        <li> Sortable, Editable requests and offers with clear rules</li>
        <li>... </li>
      </ul>
    </>
  );
}
